import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";
import Navbar from "./_components/Home/Navbar";
import Footer from "./_components/Home/Footer";
import { Toaster } from "sonner";
import { ConnectUserToConvex } from "./ConnectUserToConvex";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smart and Modular Living",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClientProvider>
      <ClerkProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden min-h-screen`}
          >
            <ConnectUserToConvex/>
            <Navbar />
            <Toaster richColors position="top-center" expand={true}/>
            {children}
            <Footer/>
          </body>
        </html>
      </ClerkProvider>
    </ConvexClientProvider>
  );
}
